services:
  - type: web
    name: flexfume-ecom-backend
    runtime: go
    plan: standard
    buildCommand: go build -o bin/server cmd/api/main.go
    startCommand: ./bin/server
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: API_PORT
        value: 8080
      - key: DB_SSLMODE
        value: require
      - key: DB_TIMEZONE
        value: UTC
      - key: GIN_MODE
        value: release
      # Database - Set these in Render dashboard
      - key: DB_HOST
        fromDatabase:
          name: flexfume-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: flexfume-db
          property: port
      - key: DB_USER
        fromDatabase:
          name: flexfume-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: flexfume-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: flexfume-db
          property: database
      # Secrets - Set these in Render dashboard
      - key: JWT_SECRET
        sync: false
      - key: REDIS_HOST
        sync: false
      - key: REDIS_PORT
        sync: false
      - key: REDIS_PASSWORD
        sync: false
      - key: SMS_URL
        sync: false
      - key: SMS_API_KEY
        sync: false
      - key: SMS_SENDER_ID
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        sync: false
      - key: AWS_S3_BUCKET_NAME
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
    routes:
      - path: /
        matchType: prefix

databases:
  - name: flexfume-db
    databaseName: flexfume_db
    user: flexfume_user
    plan: standard
    postgresMajorVersion: 15
